### PR TITLE
Story/pmg 168 list of candidates cards

### PR DESCRIPTION
**Pull request by joseiba**
## Description

Added cards to the list of candidates instead of tables, changed the internal search engine of the page, added an add icon instead of a button.

## Motivation and Context

The cards show a photo of a candidate, which is best seen by a recruiter to remind him or her of a certain candidate for future company actions.

## How Has This Been Tested?

Manually.
- Using the application from the Google Chrome v79 browser.

- Verifying that the component performs its function.

- Running as a mobile device in the browser.

### Do you have any tests?
- [ ] Yes
- [x] No

### CODE REVIEW

**Review by sofiarivas93 — CHANGES_REQUESTED** [review]
It is necessary that the search for candidates to work correctly.
The hover of the photo would be nice to put on the whole card instead of just the profile picture.

**Comment by joseiba** [comment]
> It is necessary that the search for candidates to work correctly.
> The hover of the photo would be nice to put on the whole card instead of just the profile picture.

The search is not yet defined as it would be the implementation, because there are two options that is a sort by or search that is left for the next story. We only put the search to see how it looks in the interface.

**Review by sofiarivas93 — CHANGES_REQUESTED** [review]
When functionality is not finished it is better to hide that option or else the user could identify as an error on the page.

**Comment by joseiba** [comment]
> When functionality is not finished it is better to hide that option or else the user could identify as an error on the page.



> When functionality is not finished it is better to hide that option or else the user could identify as an error on the page.

Ok, thanks

**Review by sofiarivas93 — APPROVED** [review]

**Review by rodrigovelazq — APPROVED** [review]

**Pull request merged**
