### PR TITLE
Feature/pmg 154 change age by date of birth

### PR DESCRIPTION
**Pull request by joseiba**
## Description

Change the candidate's year field to the candidate's date of birth.

## Motivation and Context

The year field was not validated and could admit negative numbers..

## How Has This Been Tested?

The changes made were checked manually, and the field was checked.

### Do you have any tests?
- [ ] Yes
- [x] No

### CODE REVIEW

**Review by sofiarivas93 — DISMISSED** [review]

**Review by rodrigovelazq — COMMENTED** [review]
I recommend that the age column be removed from the candidate table since it is no longer useful

**Comment by joseiba** [comment]
> Recomiendo que la columna de edad se elimine de la tabla de candidatos, ya que ya no es útil.

Even if you do not accept this PR, there are still changes to be made and it will create conflicts. Tomorrow I will continue with the changes

**Comment by joseiba** [comment]
> I recommend that the age column be removed from the candidate table since it is no longer useful

Even if you do not accept this PR, there are still changes to be made and it will create conflicts. Tomorrow I will continue with the changes

**Comment by joseiba** [comment]
> > I recommend that the age column be removed from the candidate table since it is no longer useful
> 
> Even if you do not accept this PR, there are still changes to be made and it will create conflicts. Tomorrow I will continue with the changes

You can now accept this PR, changes are made

**Review by rodrigovelazq — APPROVED** [review]

**Review by sofiarivas93 — APPROVED** [review]

**Pull request merged**
